services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=ecoswap'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=yes'
    ports:
      - '3306:3306'
